<?php

require_once __DIR__ . '/../ProjectCategory.php';

// Content entry conventions: see content/CONTENT_STYLE_GUIDE.md

return [
    'posts' => [
        'Chlorine in Your Tap Water Isn\'t the Problem' => [
            'url' => 'chlorine-drinking-water.md',
            'date' => '07/29/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f6b0.svg',
            'smallText' => 'Countries like Switzerland often skip chlorine residuals not because chlorine is bad, but because their infrastructure is good enough not to need it. The US is different. Until we invest in better systems, chlorine is doing its job.',
        ],
        'The Growing Problem With Li-ion Batteries in Hot Climates' => [
            'url' => 'lion-battery-heat-problem.md',
            'date' => '06/25/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f50b.svg',
            'smallText' => 'Modern power tool batteries like Ryobi switched from NiMH to Li-ion, but there\'s a problem: they can\'t handle Texas heat. What you need to know about thermal limits, fire bags, and safe storage.',
        ],
        'Mentees' => [
            'url' => 'mentees.md',
            'date' => '07/17/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f393.svg',
            'smallText' => 'A running mentorship log across Bronc Botz, SwRI YES, and independent-study students working on projects from Fortran-to-Julia benchmarks to spaceflight hardware testing.',
        ],
        'Over-the-air Motorized TV Antenna unnecessary' => [
            'url' => 'motorized-tv-antenna-spurs-games.md',
            'date' => '05/24/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4e1.svg',
            'smallText' => 'I almost built an ESP32 antenna rotator for Spurs OTA games, then realized all major local stations come from about the same direction.',
        ],
        'Modernizing My ASUS U46E i7' => [
            'url' => 'modernizing-asus-u46e-i7.md',
            'date' => '05/22/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fedora/fedora-original.svg',
            'smallText' => 'Reviving an old ASUS U46E with an SSD, AC 7265 5 GHz Wi-Fi, Fedora upgrades, and external-display troubleshooting.',
        ],
        'SVN2GIT' => [
            'url' => 'svn2git.md',
            'date' => '11/21/2023',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg',
            'smallText' => 'Convert SVN repo to Git',
        ],
        'Windows tmp on startup' => [
            'url' => 'windows-tmp-on-startup.md',
            'date' => '04/01/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/powershell/powershell-original.svg',
            'smallText' => 'A tiny PowerShell startup script that clears C:\\tmp so Windows behaves more like Linux /tmp.',
        ],
        'Git + LFS Stuck File Quick Fix' => [
            'url' => 'lfs-fix.md',
            'date' => '05/07/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg',
            'smallText' => 'A quick runbook for fixing Git LFS pull failures caused by remote and endpoint mismatches.',
        ],
        'Steam on Linux' => [
            'url' => 'steam-on-linux.md',
            'date' => '03/09/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/linux/linux-original.svg',
            'smallText' => 'Fix White Screen of Death launching Steam games on Fedora 43. Also fixes laggy Big Picture Mode.',
        ],
        'CentOS_PHP_7-8' => [
            'url' => 'PHP_Upgrade_7-8.md',
            'date' => '12/27/2023',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg',
            'smallText' => 'RHEL (e.g. CentOS) guide to upgrading PHP from 7 to 8',
        ],
        'CakePHP Framework Upgrades: 2.x → 3.x → 4.x' => [
            'url' => 'cakephp-upgrading.md',
            'date' => '08/24/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cakephp/cakephp-original.svg',
            'smallText' => 'Strategies and gotchas for upgrading CakePHP across major versions, including the critical JsHelper migration.',
        ],
        'FIRST Robotics' => [
            'url' => 'FIRST.md',
            'date' => '08/15/2023',
            'img' => '/frclocks_archive/FIRST_Horz_RGB.png',
            'smallText' => 'Former FTC and FRC Student; now mentor BroncBotz 3481, FTC 4008/6976/4602, and TMI FTC 6221.',
        ],
        'Car Diagnostics Logger' => [
            'url' => 'car-diagnostics-logger.md',
            'date' => '12/15/2015',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/raspberrypi/raspberrypi-original.svg',
            'smallText' => 'A Raspberry Pi-based OBD-II car diagnostics monitor and logger, built for privacy-oriented collection of vehicle metrics like RPM, temperatures, tire pressures, and engine codes.',
        ],
        'DIY Circuits' => [
            'url' => 'diy-circuits.md',
            'date' => '08/15/2023',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/26a1.svg',
            'smallText' => 'A personal project to create printed circuit boards (PCBs) at home, born out of necessity during COVID-19 when access to the UT Austin Makerspace was restricted.',
        ],
        'Intelligent Quads' => [
            'url' => 'intelligent-quads.md',
            'date' => '08/15/2023',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg',
            'smallText' => 'Co-founded Intelligent Quads (IQ), a modular and customizable drone platform startup spun off from Texas Aerial Robotics, enabling companies and researchers to build innovative drone applications.',
        ],
        'Hybrid-Hybrid Kubernetes Cluster' => [
            'url' => 'hybrid-kubernetes-spacecraft-web-applications.md',
            'date' => '10/15/2023',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kubernetes/kubernetes-original.svg',
            'smallText' => 'Deploying spacecraft web applications in a hybrid Kubernetes cluster spanning on-premises servers, a high-performance computing cluster, and AWS developed at Southwest Research Institute.',
        ],
        'Aceso' => [
            'url' => 'aceso.md',
            'date' => '03/09/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg',
            'smallText' => 'Aceso: Harnessing Technology to Support Children\'s Mental Health. Senior design project combining engineering, mental health awareness, and innovation.',
        ],
        '10-Keyless RGB Keyboard' => [
            'url' => 'ee445l-10-keyless-rgb-keyboard.md',
            'date' => '07/17/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/2328.svg',
            'smallText' => 'UT Austin ECE EE445L final project: custom 10-keyless keyboard with individually addressable RGB backlighting, USB interface, and onboard macro recording.',
        ],
        '7 Habits for Mental Discipline & Self-Control' => [
            'url' => 'mental-discipline-self-control.md',
            'date' => '05/24/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f4cb.svg',
            'smallText' => 'A practical checklist for self-control: sugar reset, hydration, social feed curation, daily meditation, cold-finish showers, a weekly 3-hour disappear block, and nightly reflection.',
        ],
    ],
    'media' => [
        'CakeFest-2023' => [
            'url' => 'cakefest2023.md',
            'date' => '09/30/2023',
            'img' => 'https://cakefest.org/cakefest/img/cakefest-logo.svg',
            'imgClasses' => 'bg-info-subtle',
            'smallText' => 'Conference talk on containerization. Covers Queueing methods for long-running processes and working with parts in different programming languages. YouTube video available.',
        ],
        'CakeFest-2024' => [
            'url' => 'cakefest-2024.md',
            'date' => '07/25/2024',
            'img' => 'https://cakefest.org/cakefest/img/cakefest-logo.svg',
            'imgClasses' => 'bg-info-subtle',
            'smallText' => 'Production-minded CakePHP talk focused on scalable delivery, operations, and progressive modernization.',
        ],
        'CakeFest-2025' => [
            'url' => 'cakefest-2025.md',
            'date' => '08/10/2025',
            'img' => 'https://cakefest.org/cakefest/img/cakefest-logo.svg',
            'imgClasses' => 'bg-info-subtle',
            'smallText' => 'Talk on practical CakePHP power-ups: logging, query performance, and WebAssembly-based workflows.',
        ],
        'TMI-2026' => [
            'url' => 'tmi-2026.md',
            'date' => '04/28/2026',
            'img' => '/images/tmi-episcopal-logo.png',
            'smallText' => 'Guest talk at Texas Military Institute: "Code is the easy part." Building an engineering path after graduation.',
        ],
        'Daily Texan (UT Robotics)' => [
            'url' => 'daily-texan-2019.md',
            'date' => '02/12/2019',
            'img' => '/images/daily-texan-card.svg',
            'smallText' => 'Daily Texan coverage of the Anna Hiss Gym renovation for robotics programs, including an interview with me.',
        ],
        'SwRI: Flight Analog Testing of Alternatives to Ebonol-C' => [
            'url' => 'swri-flight-analog-testing-ebonol-c.md',
            'date' => '07/17/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f52c.svg',
            'smallText' => 'SwRI Earth and Space internal R&D feature on flight-analog testing for ultraviolet suppression alternatives used in electrostatic analyzers.',
        ],
        'Code Equity: About' => [
            'url' => 'code-equity-about.md',
            'date' => '08/24/2026',
            'img' => 'https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f393.svg',
            'smallText' => 'Code Equity is a nonprofit focused on making free computer science education possible through founders, board members, advisors, instructors, and partners.',
        ],
        'SwRI SODAS: Where We Use AI' => [
            'url' => 'swri-sodas-where-we-use-ai.md',
            'date' => '08/18/2026',
            'img' => '/SwRI_AI_Talk/img/PHPStorm.png',
            'smallText' => 'A short SwRI SODAS talk on practical AI usage: start from a demo, use the IDE to accelerate the first pass, and keep humans focused on security, integration, and deployment.',
        ],
        'SwRI: Solar Eclipse Initiative (2024, 15-R6395)' => [
            'url' => 'swri-solar-eclipse-initiative-2024.md',
            'date' => '04/08/2024',
            'img' => './medias/images/swri-solar-eclipse-initiative-2024_1.jpg',
            'smallText' => 'SwRI Earth and Space internal R&D feature for the 2024 Solar Eclipse Initiative, including outreach activities and project outcomes.',
        ],
        'SwRI: Solar Eclipse Initiative (2025, 15-R6395)' => [
            'url' => 'swri-solar-eclipse-initiative-2025.md',
            'date' => '08/16/2025',
            'img' => './medias/images/swri-solar-eclipse-initiative-2025_1.jpg',
            'smallText' => 'Continuation of the SwRI Solar Eclipse Initiative in 2025, documenting updated outreach execution and team contributions.',
        ],
        'SwRI: Prototype Cloud-Based Space Science Operations Center (15-R6277)' => [
            'url' => 'swri-prototype-cloud-space-science-ops-center.md',
            'date' => '01/01/2024',
            'img' => './medias/images/swri-prototype-cloud-space-science-ops-center_1.jpg',
            'smallText' => 'SwRI Earth and Space internal R&D feature on prototyping cloud infrastructure and services for space science operations.',
        ],
        'SwRI: New Horizons Termination Shock Preparatory Science (19-R6587)' => [
            'url' => 'swri-new-horizons-termination-shock.md',
            'date' => '08/12/2025',
            'img' => './medias/images/swri-new-horizons-termination-shock_1.jpg',
            'smallText' => 'SwRI internal R&D feature on support for New Horizons heliophysics termination shock preparatory science and related tooling updates.',
        ],
    ],
    'projects' => [
        [
            'title' => 'Aceso',
            'text' => 'Harnessing Technology to Support Children\'s Mental Health. Senior design project combining engineering and mental health awareness.',
            'years' => '2019-2020',
            'categories' => [ProjectCategory::COLLEGE, ProjectCategory::SOFTWARE, ProjectCategory::HARDWARE, ProjectCategory::COMPLETED],
            'link' => ['title' => 'Full Blog Post', 'link' => '/blog/#Aceso'],
        ],
        [
            'title' => '10-Keyless RGB Keyboard (EE445L Final Project)',
            'text' => 'UT Austin ECE EE445L Spring 2020 final project. Designed and built a custom keyboard with Gateron Brown switches, individually addressable RGB backlighting, USB interface, and onboard macro recording so key combos can type stored phrases on any computer. Created with Jason Stephen, Tianshu Huang, Umer Salman, and Victor Guo.',
            'years' => '2020-2020',
            'categories' => [ProjectCategory::COLLEGE, ProjectCategory::SOFTWARE, ProjectCategory::HARDWARE, ProjectCategory::COMPLETED],
            'link' => ['title' => 'Full Blog Post', 'link' => '/blog/#10-Keyless%20RGB%20Keyboard'],
        ],
        [
            'title' => 'Flight-Analog UV Suppression Testing (SwRI IR&D)',
            'text' => 'Contributed to research and test execution for ultraviolet suppression alternatives for spaceflight hardware and electrostatic analyzers, then used results to start vendor outreach for a potential client-facing service.',
            'years' => '2025-2025',
            'categories' => [ProjectCategory::WORK, ProjectCategory::HARDWARE, ProjectCategory::COMPLETED],
            'link' => ['title' => 'In the Media', 'link' => '/blog/#SwRI:%20Flight%20Analog%20Testing%20of%20Alternatives%20to%20Ebonol-C'],
        ],
        [
            'title' => 'Solar Eclipse Initiative (15-R6395, 2024)',
            'text' => 'Supported the 2024 Solar Eclipse Initiative through science outreach and event engagement activities, with project outcomes documented by SwRI.',
            'years' => '2024-2024',
            'categories' => [ProjectCategory::WORK, ProjectCategory::HARDWARE, ProjectCategory::COMPLETED],
            'link' => ['title' => 'In the Media', 'link' => '/blog/#SwRI:%20Solar%20Eclipse%20Initiative%20(2024,%2015-R6395)'],
        ],
        [
            'title' => 'Solar Eclipse Initiative (15-R6395, 2025)',
            'text' => 'Continued Solar Eclipse Initiative work in 2025 with updated outreach execution and project visibility through SwRI IR&D coverage.',
            'years' => '2025-2025',
            'categories' => [ProjectCategory::WORK, ProjectCategory::HARDWARE, ProjectCategory::COMPLETED],
            'link' => ['title' => 'In the Media', 'link' => '/blog/#SwRI:%20Solar%20Eclipse%20Initiative%20(2025,%2015-R6395)'],
        ],
        [
            'title' => 'Prototype Cloud-Based Space Science Ops Center (15-R6277)',
            'text' => 'Helped prototype cloud-native architecture for a space science operations center, focusing on scalable services and operational flexibility.',
            'years' => '2024-2024',
            'categories' => [ProjectCategory::WORK, ProjectCategory::SOFTWARE, ProjectCategory::COMPLETED],
            'link' => ['title' => 'In the Media', 'link' => '/blog/#SwRI:%20Prototype%20Cloud-Based%20Space%20Science%20Operations%20Center%20(15-R6277)'],
        ],
        [
            'title' => 'New Horizons Termination Shock Preparatory Science (19-R6587)',
            'text' => 'Contributed to preparatory science and tooling updates supporting New Horizons heliophysics termination shock objectives.',
            'years' => '2025-2025',
            'categories' => [ProjectCategory::WORK, ProjectCategory::SOFTWARE, ProjectCategory::COMPLETED],
            'link' => ['title' => 'In the Media', 'link' => '/blog/#SwRI:%20New%20Horizons%20Termination%20Shock%20Preparatory%20Science%20(19-R6587)'],
        ],
        [
            'title' => 'JART',
            'text' => 'Co-created a meme organizer app with a collaborator after having the idea and checking whether anyone was already building something similar. The project was eventually discontinued.',
            'years' => '2025-2025',
            'categories' => [ProjectCategory::SOFTWARE],
        ],
        [
            'title' => 'Extemp Engine',
            'text' => 'Helped Hayk Saakian test and provide feedback for an offline RSS/article downloader for high school extemporaneous speaking prep. Had independently come up with the same idea before finding his work. The goal was to replace tubs of printouts with a searchable offline computer workflow during no-internet prep time. The project was eventually discontinued.',
            'years' => '2013-2014',
            'categories' => [ProjectCategory::SOFTWARE],
        ],
    ],
];
